### ISSUE TITLE
How to enable autoreload when running in a docker container?

### ISSUE THREAD

**Issue by ohmeow** [Kludex/starlette#603]
I have this in my `server.py` ...

```
if __name__ == '__main__':
    if 'serve' in sys.argv:
        uvicorn.run(app=app, host='0.0.0.0', port=5000, log_level="info")
```

... which I've learned cannot be used to enable auto-reloading.  For that, I'm told I have to actually run uvicorn from the terminal as such:

```
uvicorn example:app --debug (or I think its --reload now)
```

Anyhow, is there any way I can do the auto-reload when the application is running in a docker container. I've played with the `Dockerfile` and my `docker-compose.yml` file to see if I can make this work but so far I've been unsuccessful.

**Comment by euri10** [comment]
reload kwarg in your 1st run command should make it,
I'm sure you are already doing it, but use volumes as well since you are in
a container.

**Comment by ohmeow** [comment]
Thanks. Yah this works ...

```
uvicorn.run("server:app", host='0.0.0.0', port=5000, log_level="info", reload=True)
```

BUT, I started getting a strange error when I did this: **RuntimeError: this event loop is already running.**

It was only getting thrown when running with `reload=True` and it was because of this code ...

```
loop = asyncio.get_event_loop()
tasks = [asyncio.ensure_future(setup_learner())]
learn = loop.run_until_complete(asyncio.gather(*tasks))[0]
loop.close()
```

I was able to get around it by 1) installing `nest_asyncio` and 2) commenting out the `loop.close()` line above.

I'm still relatively new to starlette and not sure why I had to do the above to get reload to work, if what I did was even right, or if there is a better way to solve my issues.  If you have any feedback on my fix and/or can suggest a better way I'm all ears.

Thanks much

**Comment by rajeshyogeshwar** [comment]
What I do is not fire the run command in the file itself. I create a small bash script where I include the command as below.
![Screenshot from 2019-08-19 17-56-52](https://user-images.githubusercontent.com/7311146/63265240-cc571a00-c2aa-11e9-9467-777864292ac7.png)

In my docker file I copy this bash script into my container and run from there. Below is snap of my Dockerfile.

![Screenshot from 2019-08-19 17-58-26](https://user-images.githubusercontent.com/7311146/63265332-03c5c680-c2ab-11e9-9549-9223ca49473f.png)

Also, I have shared volumes, the one where my code is to a path in container. I certainly hope I didn't confuse. :)

**Comment by ohmeow** [comment]
That's a nice solution @rajeshyogeshwar .  I seen some folks using FastAPI doing something similar.

I was actually able to set things up so that only when locally development does it include the `--reload` flag via my `docker-compose.yml` file.  For folks that are interested, here's the relevant code:

Dockerfile:
```
FROM python:3.7-slim-stretch

RUN apt-get update && apt-get install -y git python3-dev gcc \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --upgrade -r requirements.txt

COPY app app/
RUN python app/server.py

EXPOSE 5000
CMD ["python", "app/server.py", "serve"]
```

docker-compose.yml
```
version: "3"
services:
  web:
    image: my-image
    # override Dockerfile CMD to enable auto-reload 
    # (see https://nickjanetakis.com/blog/docker-tip-8-overriding-your-dockerfiles-cmd)
    command: ["python", "app/server.py", "serve", "reload"]
    # map port 4000 to 5000 (the port the container exposes)
    ports:
      - '4000:5000'
    # Mount the current directory into `/app` inside the running container.
    volumes:
      - './app:/app'
```

server.py
```
if __name__ == '__main__':
    if 'serve' in sys.argv:
        reload = True if 'reload' in sys.argv else False
        uvicorn.run("server:app", host='0.0.0.0', port=5000, log_level="info", reload=reload, loop='asyncio')

```

I still have to keep that `loop.close()` line commented out or I get exceptions (not sure if this is creating an unseen problem or will, but so far, everything has been working well).
